local keymap = vim.api.nvim_set_keymap
keymap('n', 'gp',':e#<CR>',{})
keymap('n', 'gt', '<cmd>lua vim.lsp.buf.declaration()<CR>', {})
keymap('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', {})
keymap('n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', {})
keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', {})
keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', {})
keymap('n', '<leader>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', {})
keymap('n', '<leader>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', {})
keymap('n', '<leader>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', {})
keymap('n', '<leader>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', {})
keymap('n', '<leader>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', {})
keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', {})
keymap('n', '<leader>f', '<cmd>lua vim.lsp.buf.formatting()<CR>', {})
keymap('n', '<leader>e', '<cmd>:Lex 30<CR>', {})
keymap('n', '<leader>n', '<cmd>:set nonumber! | :set norelativenumber!<CR>', {})
keymap('n', '<tab>f', '<cmd>:Telescope find_files<CR>', {})
